export const CONSTANTS = {
  APP_NAME: "MathsNet",
  USER_TYPES: {
    STUDENT: "1",
    INSTRUCTOR: "2",
    ADMIN: "3",
  },
  RASTAARC: {
    GITHUB: "https://www.github.com/rastaarc",
    TWITTER: "https://www.twitter.com/rastaarcl",
  },
  USER_TYPES_TEXT: ["Student", "Instructor", "Admin"],
  ROUTES: {
    BASE_URL: "http://localhost:3000/api/",
    ADMIN: {
      ADD_COURSE: "admin/add/class",
      UPDATE_COURSE: "admin/update/class",
      DELETE_COURSE: "admin/delete/class",
      GET_COURSES: "admin/get/classes",
      ADD_SUBSCRIPTION: "admin/add/subscription",
      UPDATE_SUBSCRIPTION: "admin/update/subscription",
      DELETE_SUBSCRIPTION: "admin/delete/subscription",
      GET_SUBSCRIPTIONS: "admin/get/subscriptions",
      GET_BASIC_REVIEWS: "admin/get/reviews/basic",
      ADD_INSTRUCTOR: "admin/add/instructor",
      GET_INSTRUCTORS: "admin/get/instructors",
      ADD_STUDENT: "admin/add/student",
      GET_STUDENTS: "admin/get/students",
      LOAD_PAYMENTS: "admin/load/payments",
    },
    STUDENT: {
      ADD_PAYMENT: "student/add/payment",
      UPDATE_PAYMENT: "student/update/payment",
      ADD_COURSE: "student/add/class",
      ADD_REVIEW: "student/add/review",
      ADD_SUBSCRIPTION: "student/add/subscription",
      LOAD_PAYMENTS: "student/load/payments",
      LOAD_COURSES: "student/load/classes",
      LOAD_SUBSCRIPTIONS: "student/load/subscriptions",
      CHECK_SUBSCRIPTION_STATUS: "student/check/subscription/status",
      CHECK_COURSE_STATUS: "student/check/class/status",
      CHECK_REVIEW_STATUS: "student/check/review/status",
    },
    INSTRUCTOR: {
      GET_TOPICS: "instructor/get/topics",
      ADD_TOPIC: "instructor/add/topic",
      UPDATE_TOPIC: "instructor/update/topic",
      DELETE_TOPIC: "instructor/delete/topic",
    },
    GENERAL: {
      GET_COURSES: "get/classes",
      GET_COURSE_DATA: "get/class/data",
      GET_TOPIC_DATA: "get/topic/data",
      GET_RANDOM_COURSES: "get/random/classes",
      UPDATE_PROFILE: "update/profile",
      GET_SUBSCRIPTIONS_DATA: "get/subscriptions/data",
      UPDATE_DP_LINK: "update/dp/link",
      VALIDATE_PAYMENT: "/validate/payment",
      LOAD_COMMENTS: "/load/comments",
    },
    AUTH: {
      LOGIN: "auth/login",
      SIGNUP: "auth/signup",
      LOGOUT: "auth/logout",
      USER: "auth/get-user",
      GENERATE_RECOVERY_TOKEN: "auth/generate/recovery/token",
      UPDATE_PASSWORD: "auth/update/user/password",
    },
  },
  ALLOWED_EXTENSIONS_FOR_DP: ["jpeg", "jpg", "png"],
  ALLOWED_FILE_SIZE_DP: 1024 * 80, // 80kb
  MESSAGES: {
    INVALID_REQUEST: "Invalid Request",
    NO_VALID_CREDENTIALS: "No credentials supplied, Please try again",
    INVALID_CREDENTIALS:
      "Sorry! Invalid credentials supplied, Please try again",
    NEW_ACCOUNT_SUCCESSFUL: "Account created successfully",
    LOGOUT_SUCCESSFUL: "Your account has been logged out successfully",
    UNKNOWN_ERROR: "Unknown Error occurred. Please try again",
    INVALID_USERNAME: "Invalid Username supplied. Please choose another one",
    LOGIN_SUC: "Account Logged-in successfully",
    LOGIN_ERR: "Sorry, Your username/email or password is incorrect",
    NO_USER: "Sorry, We can't find the User with the detail(s) supplied",
    USER_EXIST:
      "Sorry! This Username has been registered. Choose another one for your account",
    EMAIL_EXIST:
      "Sorry! This Email has been registered. Choose another one for your account",
    FORM_ERROR: "Please fill the form properly",
    LOGIN_REQUIRED: "Please login first before you can access that page",
    ADMIN_REQUIRED: "Sorry! only Admin can access that page",
    INSTRUCTOR_REQUIRED: "Sorry! only Instructors can access that page",
    STUDENT_REQUIRED: "Sorry! only Students can access that page",
    ALREADY_LOGIN:
      "Please Logout first before you can have access to that page",
    FETCH_LOADING_ERROR:
      "Error Occurred while fetching the data. Please use the refresh button to reload the data",
    FETCH_LOADING_SUCCESS: "Data Fetched successfully",
    FETCH_LOADING_DATA: "Loading Data.........",
    NO_DATA_TO_DISPLAY: "SORRY! NO DATA AVAILABLE TO DISPLAY",
    NO_TOPICS_TO_DISPLAY: "No Topics Data To Display Right Now",
    COURSE_NOT_FOUND: "Oops! We can't find the Class you're looking for",
    TOPIC_NOT_FOUND: "Oops! We can't find the Topic you're looking for",
    NO_ACCESS_TO_TOPIC:
      "Oops! You don't have access to view that Class contents",
    GENERAL_ERROR_MESSAGE:
      "Oops! Something went wrong with your request. please try again",
    ADD_COURSE_FIRST: "Please add the Class to your Classes list first",
    NO_OTHER_CLASS_YET: "No other courses yet. Check back later",
    NO_TOPIC_FOR_CLASS: "No Topics for this class yet. Check back later",
    CLASS_LOGIN_REQUIRED:
      "PLEASE SIGNUP/LOGIN FIRST IN ORDER TO ADD THIS CLASS",
    NO_COURSE_DATA: "No Class Data To Display Right Now",
  },
};
